app = "fredsholm-toollib"
primary_region = "ams"

[build.compose]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 1

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1

[[mounts]]
  source = "postgres_data"
  destination = "/var/lib/postgresql/data"

[[mounts]]
  source = "mongo_data"
  destination = "/data/db"
